### ISSUE TITLE
ES-module support?

### ISSUE THREAD

**Issue by trycoon** [fastify/fastify-sensible#152]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Could we please have ES-module support instead of Common.js, now that its supported by Node.js.
<3

### Motivation

Some applications are written as ES-modules, and will have problem including this plugin if it only support common.js

`
Error starting up, error: ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/trycoon/git/vision-remix/vision-backend/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/trycoon/git/vision-remix/vision-backend/plugins/sensible.js:1:12
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at async loadPlugin (/home/trycoon/git/vision-remix/vision-backend/node_modules/@fastify/autoload/index.js:271:15)
    at async Promise.all (index 0)
    at async autoload (/home/trycoon/git/vision-remix/vision-backend/node_modules/@fastify/autoload/index.js:43:3)
`

**Comment by mcollina** [comment]
This module works with ESM, what's the issue?

```js
import fastify from 'fastify'
import sensible from '@fastify/sensible'

const app = fastify()
app.register(sensible)
```

**Comment by Fdawgs** [comment]
Closing as this is usable in ESM as given in example above.

**Comment by trycoon** [comment]
Yes, sorry, you are correct! It's was a combination of fastify-plugin and my code that triggered this error.
